// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwAzBs8JWncma7lbmJnP11TvOn8TRWT6U',
    appId: '1:884707807336:web:778769864da40c55382bdd',
    messagingSenderId: '884707807336',
    projectId: 'attendanceskl3',
    authDomain: 'attendanceskl3.firebaseapp.com',
    storageBucket: 'attendanceskl3.firebasestorage.app',
    measurementId: 'G-5LMGBQQ6N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTjqQ7e8zLarEeQRm-ev2f5AMX0WaU93k',
    appId: '1:884707807336:android:79071beccb8a3a9b382bdd',
    messagingSenderId: '884707807336',
    projectId: 'attendanceskl3',
    storageBucket: 'attendanceskl3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV_9CLRFaCMbkzIM_-aAWiE716vu5dDsE',
    appId: '1:884707807336:ios:f15cdaaf18282713382bdd',
    messagingSenderId: '884707807336',
    projectId: 'attendanceskl3',
    storageBucket: 'attendanceskl3.firebasestorage.app',
    iosBundleId: 'com.example.skl3FireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV_9CLRFaCMbkzIM_-aAWiE716vu5dDsE',
    appId: '1:884707807336:ios:f15cdaaf18282713382bdd',
    messagingSenderId: '884707807336',
    projectId: 'attendanceskl3',
    storageBucket: 'attendanceskl3.firebasestorage.app',
    iosBundleId: 'com.example.skl3FireBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwAzBs8JWncma7lbmJnP11TvOn8TRWT6U',
    appId: '1:884707807336:web:713953e36c70fbbe382bdd',
    messagingSenderId: '884707807336',
    projectId: 'attendanceskl3',
    authDomain: 'attendanceskl3.firebaseapp.com',
    storageBucket: 'attendanceskl3.firebasestorage.app',
    measurementId: 'G-VWCKX8WVFB',
  );

}